In [4]:
#using libraries 
import numpy as np     
import pandas as pd

print("numpy version",np.__version__)
print("pandas version",pd.__version__)

numpy version 1.26.4
pandas version 2.2.2


In [5]:
# create a simple 1d array
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr) 

[1 2 3 4 5]


In [6]:

import numpy as np
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
arr1
print(arr1) 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [10]:
#with print and without print
import numpy as np
#[1,2,3,4,5,6,7,8]
#np.array()
np_arr = np.array([1,2,3,4,5,6,7,8])
np_arr
#print(np_arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
# create two array
import numpy as np
#arr2 =np.array([1,2,3],[4,5,6])
arr2 =np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [20]:
#slicing array
import numpy as np
arr3 =np.array([1,2,3,4,5,6,7,8,9])
#first 4 number in array
#arr3[0:4]
#arr3[:5]
#arr3[0:]
#arr3[:]
#arr3[-1]
#end of list
#arr3[4:]
#start of array
#arr3[-1:-5]
#arr3[-5:-1]


array([5, 6, 7, 8])

In [4]:
import numpy as np
#arr4 = np.array([1,2,3,4,5,6,7,8,9,10])
#arr4[-3:]
#arr4.ndim
#arr4.size
#arr4.dtype
#arr4.itemsize
#ar = np.arrange(12).reshape(4,3)
#ar.reshape(1,15)
#ar.reshape(4,3)